#include "Vertex.h"
#include "D3DUtil.h"

IDirect3DVertexDeclaration9 *VertexPos::decl = NULL;
IDirect3DVertexDeclaration9 *VertexCol::decl = NULL;
IDirect3DVertexDeclaration9 *VertexPN::decl = NULL;
IDirect3DVertexDeclaration9 *VertexPNT::decl = NULL;
IDirect3DVertexDeclaration9 *VertexPT::decl = NULL;
IDirect3DVertexDeclaration9 *GrassVertex::decl = NULL;
IDirect3DVertexDeclaration9* Particle::decl = NULL;
IDirect3DVertexDeclaration9* NMapVertex::decl = NULL;

void InitAllVertexDeclarations()
{
	D3DVERTEXELEMENT9 vertexPosElements[] = 
	{
		{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(vertexPosElements, &VertexPos::decl));

	D3DVERTEXELEMENT9 vertexColElements[] =
	{
		{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		{0, 12, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(vertexColElements, &VertexCol::decl));

	D3DVERTEXELEMENT9 vertexPNElements[] =
	{
		{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(vertexPNElements, &VertexPN::decl));

	D3DVERTEXELEMENT9 vertexPNTElements[] =
	{
		{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0},
		{0, 24, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(vertexPNTElements, &VertexPNT::decl));

	D3DVERTEXELEMENT9 vertexPTElements[] =
	{
		{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		{0, 12, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(vertexPTElements, &VertexPT::decl));

	D3DVERTEXELEMENT9 grassVertexElements[] =
	{
		{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
		{0, 24, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 1},
		{0, 32, D3DDECLTYPE_FLOAT1, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 2},
		{0, 36, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(grassVertexElements, &GrassVertex::decl));

	D3DVERTEXELEMENT9 particleElements[] =
	{
		{0, 0,  D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
		{0, 24, D3DDECLTYPE_FLOAT1, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 1},
		{0, 28, D3DDECLTYPE_FLOAT1, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 2},
		{0, 32, D3DDECLTYPE_FLOAT1, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 3},
		{0, 36, D3DDECLTYPE_FLOAT1, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 4},
		{0, 40, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(particleElements, &Particle::decl));

	D3DVERTEXELEMENT9 NMapVertexElements[] =
	{
		{0, 0,  D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
		{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TANGENT, 0},
		{0, 24, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_BINORMAL, 0},
		{0, 36, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0},
		{0, 48, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
		D3DDECL_END()
	};
	HR(gD3dDevice->CreateVertexDeclaration(NMapVertexElements, &NMapVertex::decl));
}

void DestroyAllVertexDeclarations()
{
	ReleaseCOM(VertexPos::decl);
	ReleaseCOM(VertexCol::decl);
	ReleaseCOM(VertexPN::decl);
	ReleaseCOM(VertexPNT::decl);
	ReleaseCOM(VertexPT::decl);
	ReleaseCOM(GrassVertex::decl);
	ReleaseCOM(Particle::decl);
	ReleaseCOM(NMapVertex::decl);
}
